version: 2

sources:
    - name: staging
      database: de-zoomcamp-week1
      schema: trips_data_all

      tables:
        - name: green_tripdata
        - name: yellow_tripdata
        - name: external_fhv_tripdata
        